### ISSUE TITLE
If I clean the browser caches and cookies, I will also lose the tasks

### ISSUE THREAD

**Issue by gusbemacbe** [SimonDEvans/tempo#6]
Hello,

I did four tasks of translations time. I cleaned the caches and I lost the tasks. 
I would like to preserve the time tasks when I always clean the caches and the cookies of the browser.

**Comment by siimonevans** [comment]
@gusbemacbe unfortunately, using the browser's local storage to save tasks is a fundamental feature of the application. I won't be implementing an alternative method of storage anytime soon.
